### ISSUE TITLE
eselect repository wrong uri

### ISSUE THREAD

**Issue by MetaPhaze** [mcclung/e16-overlay#3]
using eselect repository doesn't work with your instructions... instead the instructions should be

eselect repository add e16-overlay git https://github.com/mcclung/e16-overlay.git

eselect repository add e16-overlay git https://raw.githubusercontent.com/mcclung/e16-overlay/master/repositories.xml
Adding e16-overlay to /etc/portage/repos.conf/eselect-repo.conf ...
Repository e16-overlay added

 emaint sync -r e16-overlay
>>> Syncing repository 'e16-overlay' into '/var/db/repos/e16-overlay'...
/usr/bin/git clone --depth 1 https://raw.githubusercontent.com/mcclung/e16-overlay/master/repositories.xml .
Cloning into '.'...
remote: 404: Not Found
fatal: repository 'https://raw.githubusercontent.com/mcclung/e16-overlay/master/repositories.xml/' not found
!!! git clone error in /var/db/repos/e16-overlay

altered the sync-uri like i mentioned  in the eselect-repos.conf and
nano /etc/portage/repos.conf/eselect-repo.conf

emaint sync -r e16-overlay
>>> Syncing repository 'e16-overlay' into '/var/db/repos/e16-overlay'...
/usr/bin/git clone --depth 1 https://github.com/mcclung/e16-overlay.git .
Cloning into '.'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 47 (delta 6), reused 35 (delta 2), pack-reused 0
Receiving objects: 100% (47/47), 21.22 KiB | 3.03 MiB/s, done.
Resolving deltas: 100% (6/6), done.
=== Sync completed for e16-overlay

**Comment by mcclung** [comment]
That's a nice catch, thank you.
